name: Deploy to Prod
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Test and Deploy
        run: |
          git clone https://github.com/tongzhou33/pakitong.com
          cd pakitong.com
          git checkout master
          echo "Copying files to the server"
          echo "${{ secrets.CI_SSH_KEY }}" > privkey
          chmod 600 privkey
          mkdir -p ~/.ssh/
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          echo "Creating staging area"
          ssh -i privkey ${{ secrets.USERNAME }}@${{ secrets.HOST }} "mkdir -p /tmp/deploy && rm -rf /tmp/deploy/*"
          echo "Copying files via scp"
          scp -i privkey -r . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/tmp/deploy
          echo "Deploying"
          ssh -i privkey ${{ secrets.USERNAME }}@${{ secrets.HOST }} "rm -rf /code/web && mv /tmp/deploy /code/web && rm -rf /tmp/deploy"
          echo "Deployed to the server"
          rm privkey